export const GalleryMap = {
  woowakgood: '우왁굳',
  ine: '아이네',
  jingburger: '징버거',
  lilpa: '릴파',
  jururu: '주르르',
  gosegu: '고세구',
  viichan: '비챤',
  gomem: '고멤/교멤',
  isdPick: '이세돌픽',
  halloween: '할로윈',
  rewind2year: '리와인드 2주년',
  christmas: '크리스마스',
  viichanBirthday: '비챤님 생일',
  lilpaBirthday: '릴파님 생일',
  kissingYou: '키싱유 커버',
} as const;
